In [46]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [47]:
data = pd.read_excel("titanic.xlsx")

In [48]:
data = data.drop(['name','sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked','boat', 'body', 'home.dest'], axis =1)

In [49]:
data.head()

   pclass  survived     sex      age
0       1         1  female  29.0000
1       1         1    male   0.9167
2       1         0  female   2.0000
3       1         0    male  30.0000
4       1         0  female  25.0000

In [50]:
data = data.dropna(axis = 0)

In [51]:
data.groupby(['sex']).max()

        pclass  survived   age
sex
female       3         1  76.0
male         3         1  80.0

In [52]:
data['age']

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...
1301    45.5000
1304    14.5000
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1046, dtype: float64

In [53]:
#data = data.set_index('name')
#data['age']

In [54]:
data['age'][0:10]          # INDEXING

0    29.0000
1     0.9167
2     2.0000
3    30.0000
4    25.0000
5    48.0000
6    63.0000
7    39.0000
8    53.0000
9    71.0000
Name: age, dtype: float64

In [55]:
data['age']<18         # BO0LENNE INDEXING   qui genère un masque

0       False
1        True
2        True
3       False
4       False
        ...
1301    False
1304     True
1306    False
1307    False
1308    False
Name: age, Length: 1046, dtype: bool

In [56]:
data[data['age'] < 18]   # ON A QUE DES PASSAGER MINEUR

      pclass  survived     sex      age
1          1         1    male   0.9167
2          1         0  female   2.0000
53         1         0    male  17.0000
54         1         1    male  11.0000
55         1         1  female  14.0000
...      ...       ...     ...      ...
1265       3         0  female  10.0000
1275       3         0    male  16.0000
1279       3         0  female  14.0000
1300       3         1  female  15.0000
1304       3         0  female  14.5000

[154 rows x 4 columns]

In [57]:
data[data['age'] < 18]['pclass'].value_counts()

pclass
3    106
2     33
1     15
Name: count, dtype: int64

In [58]:
data[data['age'] < 18].groupby(['sex', 'pclass']).mean()

               survived        age
sex    pclass
female 1       0.875000  14.125000
       2       1.000000   8.273150
       3       0.543478   8.416667
male   1       0.857143   9.845243
       2       0.733333   6.222220
       3       0.233333   9.838888

In [59]:
data.iloc[0:2,0:2]

   pclass  survived
0       1         1
1       1         1

In [60]:
data.loc[0:2, ['age', 'sex']]   # INDEXING SUR UNE COLONNE

       age     sex
0  29.0000  female
1   0.9167    male
2   2.0000  female